export const ACTION_TYPES = {
  GET_PHOTOS: "GET_PHOTOS",
  GET_PHOTO: "GET_PHOTO",
  UPDATE_PHOTO: "UPDATE_PHOTO",
  DELETE_PHOTO: "DELETE_PHOTO",
  CREATE_PHOTO_GROUP: "CREATE_PHOTO_GROUP",
  CREATE_PHOTO_COSTUME: "CREATE_PHOTO_COSTUME",
  CREATE_PHOTO_ADD_MEMBER: "CREATE_PHOTO_ADD_MEMBER",
  CREATE_PHOTO_DEL_MEMBER: "CREATE_PHOTO_DEL_MEMBER",
  CREATE_PHOTO_TYPE_NUMBER: "CREATE_PHOTO_TYPE_NUMBER",
  CREATE_PHOTO_INSTANCE: "CREATE_PHOTO_INSTANCE",
  CREATE_CLEAR: "CREATE_CLEAR",
  DISPLAY_PHOTO_MODAL: "DISPLAY_PHOTO_MODAL",
  HIDE_PHOTO_MODAL: "HIDE_PHOTO_MODAL",
  EDIT_PHOTO_NUMBER: "EDIT_PHOTO_NUMBER",
  CHANGE_SORT_TYPE: "CHANGE_SORT_TYPE",
  SEARCH_PHOTO: "SEARCH_PHOTO"
};

export const STORE_TYPES = {
  STATE: {
    TOP: {
      META: "top",
      PHOTOS: "photos",
      PHOTO_MODAL: "photoModal",
      SORT_TYPE: "sortType",
      KEYWORD_SEARCH: "keywordSearch"
    },
    CREATE: {
      META: "create",
      GROUP: "group",
      COSTUME: "costume",
      MEMBER: "member"
    }
  }
};

export const SORT_TYPES = {
  CREATE_TIME: "createTime",
  CREATE_TIME_REVERSE: "createTimeReverse",
  MEMBER: "member",
  MEMBER_REVERSE: "memberReverse",
  COSTUME: "costume",
  COSTUME_REVERSE: "costumeReverse"
};

export const END_POINTS = {
  PHOTO: "/photo"
};
